[package]
name = "qstudio"
version = "0.1.0"
edition.workspace = true

[dependencies]
engine = { path = "../engine" }
eframe = "0.32.0"
egui = "0.32.0"
env_logger = "0.11.8"
egui_code_editor = {path = "./egui_code_editor"}
egui_dock = "0.17.0"
egui_commonmark = "0.21.1"
rand = "0.9.2"
tokio = { version = "1.46.1", features = ["full"] }
polars = "0.49.1"
egui_extras = "0.32.0"
rfd = "0.15.4"
egui_plot = "0.33.0"
