name: Release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --workspace
      - name: Package artifacts
        run: |
          mkdir -p dist
          cp target/release/qstudio dist/
          cp target/release/engine-server dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
